---

- hosts: dev-vagrant

  vars_files:
    - vars/postgres_vars.yml

  roles:
    - { role: java8, become: yes }
    - { role: nodejs, become: yes }
    - { role: scala, become: yes }
    - { role: sbt, become: yes }
    - { role: postgres, become: yes }
