---

- hosts: dev-vagrant
  roles:
    - { role: java8, become: yes }
    - { role: nodejs, become: yes }
    - { role: scala, become: yes }
    - { role: sbt, become: yes }
    - { role: postgres, become: yes }
