---

- name: Run apt-get update for postgres libs
  apt: update_cache=yes

- name: Install postgres
  apt:
    name: postgresql
    state: latest

- name: Install postgres-contrib
  apt:
    name: postgresql-contrib
    state: latest

- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: latest

- name: Install python-psycopg2
  apt:
    name: python-psycopg2
    state: latest

- name: Create database
  postgresql_db: name={{ db_name }}
  become_user: postgres

- name: Create user
  postgresql_user: db={{ db_name }}  name={{ db_username }} password={{ db_password }} priv=ALL
  become_user: postgres

- name: Remove unnecessary privileges
  postgresql_user: name={{ db_username }} role_attr_flags=NOSUPERUSER,NOCREATEDB
  become_user: postgres

- name: Ensure no other user can access the database
  postgresql_privs: db={{ db_name }}  role=PUBLIC type=database priv=ALL state=absent
  become_user: postgres
