---

- name: Run apt-get update for postgres libs
  apt: update_cache=yes

- name: Install postgres
  apt:
    name: postgresql
    state: latest

- name: Install postgres-contrib
  apt:
    name: postgresql-contrib
    state: latest

- name: Install libpq-dev
  apt:
    name: libpq-dev
    state: latest

- name: Install python-psycopg2
  apt:
    name: python-psycopg2
    state: latest

- name: Create database
  postgresql_db: name=personate

- name: Create user
  postgresql_user: db=personate name=vagrant password=vagrantpassword priv=ALL

- name: Remove unnecessary privileges
  postgresql_user: name=vagrant role_attr_flags=NOSUPERUSER,NOCREATEDB

- name: Ensure no other user can access the database
  postgresql_privs: db=personate role=PUBLIC type=database priv=ALL state=absent
